
x-base-app-conf: &base_app_conf
  env_file: .env.prod
  stdin_open: true
  tty: true

services:
  # FastAPI application
  fasthtmx_app:
    <<: *base_app_conf
    image: fasthtmx_app:latest
    container_name: fasthtmx_app
    restart: always
    build:
      context: .
      dockerfile: compose/production/Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ["/bin/sh", "./compose/production/entrypoint.sh"]
    command: ["/bin/sh", "./compose/production/start.sh"]

  # Celery service
  celery:
    <<: *base_app_conf
    image: fasthtmx_app:latest
    container_name: fasthtmx_celery
    entrypoint: ["/bin/sh", "./compose/production/entrypoint.sh"]
    command: ["/bin/sh", "./compose/production/celery/start_celery.sh"]
    depends_on:
      - db

  # Celery worker
  worker:
    <<: *base_app_conf
    image: fasthtmx_app:latest
    container_name: fasthtmx_worker
    entrypoint: ["/bin/sh", "./compose/production/entrypoint.sh"]
    command: ["/bin/sh", "./compose/production/worker/start_worker.sh"]
    depends_on:
      - celery

  # Flower monitoring for Celery
  flower:
    <<: *base_app_conf
    image: fasthtmx_app:latest
    container_name: fasthtmx_flower
    entrypoint: ["/bin/sh", "./compose/production/entrypoint.sh"]
    command: ["/bin/sh", "./compose/production/flower/start_flower.sh"]
    ports:
      - "5555:5555"
    depends_on:
      - celery
