"""empty message

Revision ID: f530034cf2a8
Revises: 44e214c20c98
Create Date: 2024-10-07 16:18:47.891399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f530034cf2a8'
down_revision: Union[str, None] = '44e214c20c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('bucket_name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('encryption_type', sa.String(), nullable=True),
    sa.Column('kms_alias', sa.String(), nullable=True),
    sa.Column('policy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s3_buckets_account_id'), 's3_buckets', ['account_id'], unique=False)
    op.create_index(op.f('ix_s3_buckets_bucket_name'), 's3_buckets', ['bucket_name'], unique=True)
    op.create_index(op.f('ix_s3_buckets_id'), 's3_buckets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_s3_buckets_id'), table_name='s3_buckets')
    op.drop_index(op.f('ix_s3_buckets_bucket_name'), table_name='s3_buckets')
    op.drop_index(op.f('ix_s3_buckets_account_id'), table_name='s3_buckets')
    op.drop_table('s3_buckets')
    # ### end Alembic commands ###
