"""empty message

Revision ID: 336b0253c2e4
Revises: 
Create Date: 2024-10-07 03:09:19.781354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336b0253c2e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('role_arn', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_aws_accounts_id'), 'aws_accounts', ['id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('target_account_id', sa.String(), nullable=True),
    sa.Column('target_region', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('kms_key_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_snapshots_snapshot_id'), 'snapshots', ['snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_snapshot_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_aws_accounts_id'), table_name='aws_accounts')
    op.drop_table('aws_accounts')
    # ### end Alembic commands ###
